---
  - name: Upload .tar.gz file containing binaries from local storage
    copy:
      src: "{{ kibana_package }}"
      dest: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
    register: download_kibana_binaries
    until: download_kibana_binaries is succeeded
    tags: kibana
  - name: Ensure installation dir exists
    become: true
    file:
      state: directory
      path: "{{ kibana_home }}"
    tags: kibana
  - name: Extract kibana in the installation directory
    become: true
    unarchive:
      copy: false
      src: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
      dest: "{{ kibana_home }}"
      extra_opts: [--strip-components=1]
      creates: "{{ kibana_home }}/bin/kibana"
    tags:
      - skip_ansible_lint
      - kibana
  - name: Export environment variables
    become: true
    template:
      src: kibana.sh.j2
      dest: /etc/profile.d/kibana.sh
    tags: kibana
  #"завладеем" каталогом с кибаной, чтобы она нормально работала
  - name: Recursively take ownership of a directory
    become: yes      
    file:
      path: "{{ kibana_home }}"
      state: directory
      recurse: yes
      owner: "root"
      group: "root"
  #разрешим доступ к кибане по ip сервера, а не только по localhost
  - name: Make Kibana avalaible on any interface
    lineinfile:
      path: "{{ kibana_home }}/config/kibana.yml"
      line: 'server.host: "0.0.0.0"'